import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import HomeNavbar from "@/components/providers/HomeNavbar";
import { NextIntlClientProvider } from "next-intl";

import "./globals.css";
import { getMessages } from "next-intl/server";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const { locale } = params;

  const messages = await getMessages();

  return (
    <html lang={locale} suppressHydrationWarning className="dark">
      <body
        className={`${poppins.className} bg-background w-full min-h-full h-full mx-auto scroll-smooth overflow-x-hidden antialiased`}
      >
        <NextIntlClientProvider messages={messages}>
          <HomeNavbar />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
